import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from './_utils/auth-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NGO Management',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
